In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plp

In [ ]:
df=pd.read_csv("/content/AAPL.csv")
df

,Date,Open,High,Low,Close,Adj Close,Volume
0,1980-12-12,0.128348,0.128906,0.128348,0.128348,0.100323,469033600
1,1980-12-15,0.122210,0.122210,0.121652,0.121652,0.095089,175884800
2,1980-12-16,0.113281,0.113281,0.112723,0.112723,0.088110,105728000
3,1980-12-17,0.115513,0.116071,0.115513,0.115513,0.090291,86441600
4,1980-12-18,0.118862,0.119420,0.118862,0.118862,0.092908,73449600
...,...,...,...,...,...,...,...
10404,2022-03-18,160.509995,164.479996,159.759995,163.979996,163.979996,123351200
10405,2022-03-21,163.509995,166.350006,163.009995,165.380005,165.380005,95811400
10406,2022-03-22,165.509995,169.419998,164.910004,168.820007,168.820007,81532000
10407,2022-03-23,167.990005,172.639999,167.649994,170.210007,170.210007,98062700
10408,2022-03-24,171.059998,174.139999,170.210007,174.070007,174.070007,90018700

In [ ]:
print(df.head())

         Date      Open      High       Low     Close  Adj Close     Volume
0  1980-12-12  0.128348  0.128906  0.128348  0.128348   0.100323  469033600
1  1980-12-15  0.122210  0.122210  0.121652  0.121652   0.095089  175884800
2  1980-12-16  0.113281  0.113281  0.112723  0.112723   0.088110  105728000
3  1980-12-17  0.115513  0.116071  0.115513  0.115513   0.090291   86441600
4  1980-12-18  0.118862  0.119420  0.118862  0.118862   0.092908   73449600

In [ ]:
print(df.info)

<bound method DataFrame.info of              Date        Open        High         Low       Close   Adj Close  \
0      1980-12-12    0.128348    0.128906    0.128348    0.128348    0.100323
1      1980-12-15    0.122210    0.122210    0.121652    0.121652    0.095089
2      1980-12-16    0.113281    0.113281    0.112723    0.112723    0.088110
3      1980-12-17    0.115513    0.116071    0.115513    0.115513    0.090291
4      1980-12-18    0.118862    0.119420    0.118862    0.118862    0.092908
...           ...         ...         ...         ...         ...         ...
10404  2022-03-18  160.509995  164.479996  159.759995  163.979996  163.979996
10405  2022-03-21  163.509995  166.350006  163.009995  165.380005  165.380005
10406  2022-03-22  165.509995  169.419998  164.910004  168.820007  168.820007
10407  2022-03-23  167.990005  172.639999  167.649994  170.210007  170.210007
10408  2022-03-24  171.059998  174.139999  170.210007  174.070007  174.070007

          Volume
0      469033600
1      175884800
2      105728000
3       86441600
4       73449600
...          ...
10404  123351200
10405   95811400
10406   81532000
10407   98062700
10408   90018700

[10409 rows x 7 columns]>

In [ ]:
df = df.dropna()
df = df.drop_duplicates()
df

,Date,Open,High,Low,Close,Adj Close,Volume
0,1980-12-12,0.128348,0.128906,0.128348,0.128348,0.100323,469033600
1,1980-12-15,0.122210,0.122210,0.121652,0.121652,0.095089,175884800
2,1980-12-16,0.113281,0.113281,0.112723,0.112723,0.088110,105728000
3,1980-12-17,0.115513,0.116071,0.115513,0.115513,0.090291,86441600
4,1980-12-18,0.118862,0.119420,0.118862,0.118862,0.092908,73449600
...,...,...,...,...,...,...,...
10404,2022-03-18,160.509995,164.479996,159.759995,163.979996,163.979996,123351200
10405,2022-03-21,163.509995,166.350006,163.009995,165.380005,165.380005,95811400
10406,2022-03-22,165.509995,169.419998,164.910004,168.820007,168.820007,81532000
10407,2022-03-23,167.990005,172.639999,167.649994,170.210007,170.210007,98062700
10408,2022-03-24,171.059998,174.139999,170.210007,174.070007,174.070007,90018700

In [ ]:
import numpy as np
import pandas as pd

df = pd.read_excel("AAPL.xlsx")

print(df.head())

In [ ]:
print(df.tail())

In [ ]:
df.info()

In [ ]:
print(df.columns)

In [ ]:
print(df.dtypes)

In [ ]:
print(df.describe())

In [ ]:
df = df.dropna()

In [ ]:
df["Date"] = pd.to_datetime(df["Date"])

In [ ]:
df = df.sort_values("Date")

In [ ]:
print(df.head())

In [ ]:
print(df.dtypes)